# Generated by Django 4.2.3 on 2023-08-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('Sport', 'Sport'), ('Party', 'Party'), ('Food', 'Food'), ('Movie', 'Movie'), ('Theater', 'Theater'), ('Art', 'Art'), ('Science', 'Science'), ('Technology', 'Technology'), ('Business', 'Business'), ('Politics', 'Politics'), ('Education', 'Education'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Travel', 'Travel'), ('Religion', 'Religion'), ('Charity', 'Charity'), ('Music', 'Music'), ('Culture', 'Culture'), ('Other', 'Other')], default='Other', max_length=25)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='event_pics/default.png', upload_to='event_pics')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pictures', to='events.event')),
            ],
        ),
    ]
