# Generated by Django 4.2.3 on 2023-08-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventPictures',
            new_name='EventPicture',
        ),
    ]
